import Header from './../components/header.js';
import Results from './../components/results.js';
import Head from 'next/head';
import Nav from '../components/nav.js';
import requests from "../utility/request.js"
export default function Home(props) {
  return (
    <div className="home">
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Hulu Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Nav></Nav>
      <Results results={props.results}></Results>
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre;
  //const url = `https://api.themoviesdb.org/3${requests[genre]?.url || requests.fetchTrending.url}`;
  const murl =`https://mocki.io/v1/37acfc42-6dd2-4ab8-9a60-9c86161c7a21`;
  const request = await fetch(murl)
  .then(res=>{ console.log(res); return res.json()}).catch(e=> console.log(e));
  return {
    props: {
      results: request.results
    }
  }
}